language: c

cache:
  pip: true

matrix:
  include:
    - arch: amd64
      os: linux
      dist: bionic
      sudo: required
      compiler: clang
      env: TRAVIS_ARCH="amd64"
    - arch: amd64
      os: linux
      dist: bionic
      sudo: required
      compiler: gcc
      env: TRAVIS_ARCH="amd64" DEPLOY_BUILD=TRUE
    - arch: arm64
      os: linux
      dist: bionic
      sudo: required
      compiler: gcc
      env: TRAVIS_ARCH="arm64"
    - arch: amd64
      os: linux
      dist: bionic
      sudo: required
      compiler: gcc
      env: TRAVIS_ARCH="amd64"
    - arch: amd64
      os: osx
      compiler: gcc
      env: TRAVIS_ARCH="amd64"
    - arch: ppc64le
      os: linux
      dist: bionic
      sudo: required
      compiler: gcc
      env: TRAVIS_ARCH="ppc64le"
    - arch: ppc64le
      os: linux
      dist: bionic
      sudo: required
      compiler: clang
      env: TRAVIS_ARCH="ppc64le"
  allow_failures:
    - os: osx

branches:
  only:
    - master
    - devel

addons:
  apt:
    packages:
      - graphviz
      - nasm
      - valgrind
      - python3-dev
      - python3-cffi
      - python3-setuptools
      - python3-pip
      - libgtest-dev
    update: true
  homebrew:
    packages:
      - graphviz
      - nasm
      - googletest
    update: true

before_install:
  - if [ "$DEPLOY_BUILD" = "TRUE" ]; then sudo snap install universal-ctags; fi
  - if [ "$DEPLOY_BUILD" = "TRUE" ]; then pip3 install --user codecov==2.0.22; export CFLAGS="-coverage"; fi

script:
  - mkdir build && cd build
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cmake -DGCOV=OFF ..; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_ARCH" = "amd64" ]; then cmake -DGCOV=ON -DCMAKE_BUILD_TYPE=Debug ..; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_ARCH" = "arm64" ]; then cmake -DGCOV=OFF ..; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_ARCH" = "ppc64le" ]; then cmake -DGCOV=OFF ..; fi
  - make && make test > /dev/null
  - cd -

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    script: bash <(curl https://codecov.io/bash)
    skip_cleanup: true
    verbose: true
    on:
      branch: master
      condition: $DEPLOY_BUILD = TRUE
