name: benchmark

on: [push, pull_request]

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Install requirements
        run: |
          sudo apt-get update -q -y
          sudo apt-get install -q -y gcc g++ git nasm libgtest-dev openssl cmake

      - name: Configure
        run: cmake -B ${{github.workspace}}/build -DMPN_NO_ASM=ON -DBUILD_VENDOR=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build

      - name: Run Benchmark
        working-directory: ${{github.workspace}}/build
        run: |
          ${{github.workspace}}/build/tests/benchmark > ${{github.workspace}}/resource/benchmark.data || true
      
      - uses: actions/upload-artifact@v2
        with:
          name: benchmark
          path: ${{github.workspace}}/resource/benchmark.data

