name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.distro }}

    strategy:
      matrix:
        distro: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Install requirements
        run: |
          case "${{ matrix.distro }}" in
            ubuntu*|jessie|stretch|buster|bullseye)
              sudo apt-get update -q -y
              sudo apt-get install -q -y gcc g++ git nasm libgtest-dev openssl cmake
              ;;
            macos*)
              brew update
              brew install nasm googletest openssl
              brew link openssl --force
              export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
              export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
              ;;
            fedora*)
              sudo dnf -y update
              sudo dnf -y install gcc g++ git nasm gtest openssl cmake
              ;;
            alpine*)
              apk update
              apk add gcc g++ git nasm gtest openssl cmake
              ;;
          esac

      - name: Configure
        run: cmake -B ${{github.workspace}}/build -DMPN_NO_ASM=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build
