name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        build: [Release, Debug]
        compiler: [gcc, clang]
        arch: [aarch64, amd64, x86, x86_64]

    steps:
      - uses: actions/checkout@v2

      - name: Install Linux requirements
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          lscpu
          sudo apt install nasm
          sudo apt install libgtest-dev
          sudo apt install openssl

      - name: Install MacOS requirements
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew install nasm
          brew install googletest
          brew install openssl
          brew link openssl --force
          export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
          export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

      - name: Configure
        run: cmake -B ${{github.workspace}}/build -DCMAKE_C_COMPILER=$(which ${{ matrix.compiler }}) -DCMAKE_BUILD_TYPE=${{ matrix.build }}

      - name: Build
        run: cmake --build ${{github.workspace}}/build
