name: coverage

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: Linux
            build: Release
            compiler: gcc
            codecov: OFF
          - os: ubuntu-latest
            target: Linux
            build: Debug
            compiler: gcc
            codecov: ON
          - os: ubuntu-latest
            target: Linux
            build: Release
            compiler: clang
            codecov: OFF
          - os: ubuntu-latest
            target: Linux
            build: Debug
            compiler: clang
            codecov: OFF

    steps:
      - uses: actions/checkout@v2

      - name: Install Linux requirements
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt install nasm
          sudo apt install libgtest-dev
          sudo apt install openssl

      - name: Install MacOS requirements
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew install nasm
          brew install googletest
          brew install openssl

      - name: Configure
        run: cmake -B ${{github.workspace}}/build -DCMAKE_C_COMPILER=$(which ${{ matrix.compiler }}) -DGCOV=${{ matrix.codecov }} -DCMAKE_BUILD_TYPE=${{ matrix.build }} -DMPI_NO_ASM=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: make test

      - name: Upload To CodeCov
        if: ${{ matrix.codecov == 'Debug' }}
        working-directory: ${{github.workspace}}/build
        env:
          CODECOV_TOKEN: 860137d0-39de-4de2-85ed-07c0a6768ead
        run: bash <(curl -s https://codecov.io/bash)
